local MashrytLine = {
	["One_line"] = {
		["NachalStation"] = {},
		["KonechStation"] = {},
		["Stations"] = {}
	},
	["Two_line"] = {
		["NachalStation"] = {"Дустлик", "Серверный вокзал Ташкента", "Айбек", "Алишера Навои", "Бернули"},
		["KonechStation"] = {"Дустлик", "Серверный вокзал Ташкента", "Айбек", "Алишера Навои", "Бернули"},
		["Stations"] = {"Дустлик", "Машиностроительная", "Серверный вокзал Ташкента", "Айбек", "Площадь космонавтов", "Узбекистанская", "Алишера Навои", "Гафура Гуляма", "Чор-Су", "Тинчлик", "Бернули"}
	},
	["Three_line_2024"] = {
		["SoundInformatorNachToKonech"] = "rbxassetid://124956916778903",
		["SoundInformatorKonechToNach"] = "rbxassetid://115060019427765",
		["NachalStation"] = {"Лісова", "Дніпро"},
		["KonechStation"] = {"Лісова", "Дніпро", "Дарниця"},
		["StationsByN"] = {"Лісова", "Чернігівська", "Дарниця", "Лівобережна", "Гідропарк", "Дніпро"},
		["MonitorKonechStation"] = {"Lisova", "Dnipro", "Darnytsia"},
		["MonitorStations"] = {"Лісова", "Чернігівська", "Дарниця", "Лівобережна", "Гідропарк", "Дніпро"},
		["Stations"] = {
			["Чернігівська"] = { ["Next"] = 0,   ["Now"] = 20 },
			["Дарниця"]     = { ["Next"] = 40,  ["Now"] = 60 },
			["Лівобережна"] = { ["Next"] = 80,  ["Now"] = 100 },
			["Гідропарк"]   = { ["Next"] = 120, ["Now"] = 140 },
			["Дніпро"]      = { ["Next"] = 160 , ["Now"] = 180 },
		},
		["StationsB"] = {
			["Гідропарк"] = {
				["Next"] = 0,
				["Now"] = 20
			},
			["Лівобережна"] = {
				["Next"] = 40,
				["Now"] = 60
			},
			["Дарниця"] = {
				["Next"] = 80,
				["Now"] = 100
			},
			["Чернігівська"] = {
				["Next"] = 120,
				["Now"] = 140
			},
			["Лісова"] = {
				["Next"] = 160,
				["Now"] = 180
			}
		}
	},
	["Three_line_2021"] = {
		["SoundInformatorNachToKonech"] = "rbxassetid://114133059924518",
		["SoundInformatorKonechToNach"] = "rbxassetid://105814839106552",
		["NachalStation"] = {"Лісова", "Дніпро"},
		["KonechStation"] = {"Лісова", "Дніпро", "Дарниця"},
		["StationsByN"] = {"Лісова", "Чернігівська", "Дарниця", "Лівобережна", "Гідропарк", "Дніпро"},
		["MonitorKonechStation"] = {"Lisova", "Dnipro", "Darnytsia"},
		["MonitorStations"] = {"Лісова", "Чернігівська", "Дарниця", "Лівобережна", "Гідропарк", "Дніпро"},
		["Stations"] = {
			["Чернігівська"] = { ["Next"] = 0,   ["Now"] = 20 },
			["Дарниця"]     = { ["Next"] = 40,  ["Now"] = 60 },
			["Лівобережна"] = { ["Next"] = 80,  ["Now"] = 100 },
			["Гідропарк"]   = { ["Next"] = 120, ["Now"] = 140 },
			["Дніпро"]      = { ["Next"] = 160 , ["Now"] = 180 },
		},
		["StationsB"] = {
			["Гідропарк"] = {
				["Next"] = 0,
				["Now"] = 20
			},
			["Лівобережна"] = {
				["Next"] = 40,
				["Now"] = 60
			},
			["Дарниця"] = {
				["Next"] = 80,
				["Now"] = 100
			},
			["Чернігівська"] = {
				["Next"] = 120,
				["Now"] = 140
			},
			["Лісова"] = {
				["Next"] = 160,
				["Now"] = 180
			}
		}
	},
	["Four_line"] = {
		["NachalStation"] = {},
		["KonechStation"] = {},
		["Stations"] = {}
	},
	["SSV_Mashryt_One_line"] = {
		["NachalStation"] = {},
		["KonechStation"] = {},
		["Stations"] = {}
	},
	["SSV_Mashryt_Two_line"] = {
		["NachalStation"] = {},
		["KonechStation"] = {},
		["Stations"] = {}
	},
	["SSV_Mashryt_Three_line"] = {
		["NachalStation"] = {},
		["KonechStation"] = {},
		["Stations"] = {}
	}
}
return MashrytLine